### ISSUE TITLE
Trouble running example project

### ISSUE THREAD

**Issue by aiham** [dcodeIO/AssemblyScript#53] opened 2017-06-20 01:18 UTC
Hi,

I'm having trouble running the example project to compile a wasm file.

In my folder I have `module.ts`:

```ts
export function add(a: int, b: int): int {
  return a + b;
}
```

A `package.json` file:

```json
{
  "scripts": {
    "build": "asc module.ts -o module.wasm"
  },
  "devDependencies": {
    "assemblyscript": "https://github.com/dcodeIO/AssemblyScript.git"
  }
}
```

And a `tsconfig.json` file:

```
{
  "extends": "./node_modules/assemblyscript/tsconfig.assembly.json"
}
```

When I run `yarn ; yarn run build` I get:

```
yarn run v0.24.6
$ asc module.ts -o module.wasm
/private/tmp/assembly-script-hello/node_modules/assemblyscript/cli/asc/index.ts:3
import { Compiler } from "../../src/compiler";
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/private/tmp/assembly-script-hello/node_modules/ts-node/src/index.ts:376:14)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (/private/tmp/assembly-script-hello/node_modules/ts-node/src/_bin.ts:177:12)
error Command failed with exit code 1.
```

I took a look at `assemblyscript/bin/asc` and tried to run the equivalent CLI command which gives me the same error:

```sh
$ node node_modules/ts-node/dist/bin.js --project ./node_modules/assemblyscript/cli/asc ./node_modules/assemblyscript/cli/asc/index.ts module.ts -o module.wasm
/private/tmp/assembly-script-hello/node_modules/assemblyscript/cli/asc/index.ts:3
import { Compiler } from "../../src/compiler";
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/private/tmp/assembly-script-hello/node_modules/ts-node/src/index.ts:376:14)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (/private/tmp/assembly-script-hello/node_modules/ts-node/src/_bin.ts:177:12)
```

I'm using Node 8.1.2

Appreciate any help, thanks.

**Comment by dcodeIO** [comment] 2017-06-20 07:57
That's strange. Looks like the .ts file is run as a .js file for some reason.

**Comment by aiham** [comment] 2017-06-20 08:00
@dcodeIO Can you verify the arguments I'm passing into ts-node in the final snippet are correct?

**Comment by dcodeIO** [comment] 2017-06-20 08:03
Looks correct to me, but I am certainly missing something here.

**Comment by aiham** [comment] 2017-06-20 08:06
@dcodeIO I figure I'm probably missing a dependency. Do you have any globally installed modules that might be in use here? And what version of node are you currently using on this project? Also if it's of any importance, I'm using OSX.

**Comment by dcodeIO** [comment] 2017-06-20 08:09
Using node 8 as well, on win64. Not sure if this could be a TypeScript version mismatch or something.

**Comment by aiham** [comment] 2017-06-20 11:48
@dcodeIO Here's my dependency list:

```
$ yarn list
yarn list v0.24.6
├─ @protobufjs/base64@1.1.2
├─ @types/long@3.0.31
├─ @types/minimist@1.2.0
├─ @types/node@7.0.32
├─ ansi-regex@2.1.1
├─ ansi-styles@2.2.1
├─ arrify@1.0.1
├─ assemblyscript@0.0.1
│  ├─ @protobufjs/base64@^1.1.1
│  ├─ @types/long@^3.0.31
│  ├─ @types/minimist@^1.2.0
│  ├─ @types/node@^7.0.27
│  ├─ binaryen@1.37.13-nightly.20170617
│  ├─ long@^3.2.0
│  ├─ minimist@^1.2.0
│  ├─ performance-now@^2.1.0
│  ├─ ts-node@^3.0.4
│  └─ typescript@^2.4.0-dev.20170604
├─ binaryen@1.37.13-nightly.20170617
├─ chalk@1.1.3
│  ├─ ansi-styles@^2.2.1
│  ├─ escape-string-regexp@^1.0.2
│  ├─ has-ansi@^2.0.0
│  ├─ strip-ansi@^3.0.0
│  └─ supports-color@^2.0.0
├─ diff@3.2.0
├─ escape-string-regexp@1.0.5
├─ has-ansi@2.0.0
│  └─ ansi-regex@^2.0.0
├─ long@3.2.0
├─ make-error@1.3.0
├─ minimist@1.2.0
├─ mkdirp@0.5.1
│  ├─ minimist@0.0.8
│  └─ minimist@0.0.8
├─ performance-now@2.1.0
├─ source-map-support@0.4.15
│  └─ source-map@^0.5.6
├─ source-map@0.5.6
├─ strip-ansi@3.0.1
│  └─ ansi-regex@^2.0.0
├─ strip-bom@3.0.0
├─ strip-json-comments@2.0.1
├─ supports-color@2.0.0
├─ ts-node@3.0.6
│  ├─ arrify@^1.0.0
│  ├─ chalk@^1.1.1
│  ├─ diff@^3.1.0
│  ├─ make-error@^1.1.1
│  ├─ minimist@^1.2.0
│  ├─ mkdirp@^0.5.1
│  ├─ source-map-support@^0.4.0
│  ├─ tsconfig@^6.0.0
│  ├─ v8flags@^2.0.11
│  └─ yn@^2.0.0
├─ tsconfig@6.0.0
│  ├─ strip-bom@^3.0.0
│  └─ strip-json-comments@^2.0.0
├─ typescript@2.4.0
├─ user-home@1.1.1
├─ v8flags@2.1.1
│  └─ user-home@^1.1.1
└─ yn@2.0.0
✨  Done in 0.11s.
```

**Comment by dcodeIO** [comment] 2017-06-20 11:54
Hard to tell. `typescript@2.4.0` looks suspicious as that's not released yet.

**Comment by aiham** [comment] 2017-06-20 11:56
Unfortunately I can't use your package-lock.json file because [npm5 is quite buggy](https://github.com/npm/npm/issues/16991). I'm personally hitting one of these issues so I'm sticking with yarn. If you reconsider #11 then that may help me here. Thanks

**Comment by aiham** [comment] 2017-06-20 11:57
@dcodeIO Actually typescript@2.4 is in your package.json: https://github.com/dcodeIO/AssemblyScript/blob/1a61ec9a8751fa71bf06fbffaecf106742e10310/package.json#L34

**Comment by dcodeIO** [comment] 2017-06-20 12:00
Yes, but it's a prerelease snapshot, not a release.

**Comment by aiham** [comment] 2017-06-20 12:13
Yeah, 2.4.0 has been published but tagged as `rc`, not `latest`. According to https://semver.npmjs.com/ your pattern `^2.4.0-dev.20170604` matches `2.4.0`

**Comment by aiham** [comment] 2017-06-20 12:37
Using npm@5 doesn't help.

```
[22:35:20][/tmp/assembly-script-hello]$ npm install
npm WARN prefer global ts-node@3.0.6 should be installed with -g
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN assembly-script-hello No description
npm WARN assembly-script-hello No repository field.
npm WARN assembly-script-hello No license field.

added 31 packages in 3.283s
[22:35:28][/tmp/assembly-script-hello]$ npm ls
/private/tmp/assembly-script-hello
└─┬ assemblyscript@0.0.1 (git+https://github.com/dcodeIO/AssemblyScript.git#dee7ff7034961e918a3c929b59f90049d6360c05)
  ├── @protobufjs/base64@1.1.2
  ├── @types/long@3.0.31
  ├── @types/minimist@1.2.0
  ├── @types/node@7.0.32
  ├── binaryen@1.37.13-nightly.20170617
  ├── long@3.2.0
  ├── minimist@1.2.0
  ├── performance-now@2.1.0
  ├─┬ ts-node@3.0.6
  │ ├── arrify@1.0.1
  │ ├─┬ chalk@1.1.3
  │ │ ├── ansi-styles@2.2.1
  │ │ ├── escape-string-regexp@1.0.5
  │ │ ├─┬ has-ansi@2.0.0
  │ │ │ └── ansi-regex@2.1.1
  │ │ ├─┬ strip-ansi@3.0.1
  │ │ │ └── ansi-regex@2.1.1 deduped
  │ │ └── supports-color@2.0.0
  │ ├── diff@3.2.0
  │ ├── make-error@1.3.0
  │ ├── minimist@1.2.0 deduped
  │ ├─┬ mkdirp@0.5.1
  │ │ └── minimist@0.0.8
  │ ├─┬ source-map-support@0.4.15
  │ │ └── source-map@0.5.6
  │ ├─┬ tsconfig@6.0.0
  │ │ ├── strip-bom@3.0.0
  │ │ └── strip-json-comments@2.0.1
  │ ├─┬ v8flags@2.1.1
  │ │ └── user-home@1.1.1
  │ └── yn@2.0.0
  └── typescript@2.4.0

[22:35:36][/tmp/assembly-script-hello]$ npm run build

> @ build /private/tmp/assembly-script-hello
> asc module.ts -o module.wasm

/private/tmp/assembly-script-hello/node_modules/assemblyscript/cli/asc/index.ts:3
import { Compiler } from "../../src/compiler";
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/private/tmp/assembly-script-hello/node_modules/ts-node/src/index.ts:376:14)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (/private/tmp/assembly-script-hello/node_modules/ts-node/src/_bin.ts:177:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `asc module.ts -o module.wasm`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by dcodeIO** [comment] 2017-06-20 13:01
Gave this a try now and I am quite certain now that the issue is a result from something trying to run a TypeScript file as a JavaScript file. Hence, I assume that `ts-node` isn't working in your setup for some reason. You can try this yourself in a stripped down scenario:

```ts
// someFile.ts
import { Anything } from "..";
```

```
$> ts-node someFile.ts
```

Maybe this helps to pinpoint the issue.

**Comment by aiham** [comment] 2017-06-20 13:49
Thanks for giving it a go. It appears ts-node is behaving differently if the file is inside node_modules.

This works fine:

```
[23:44:25][/private/tmp/assembly-script-hello]$ cat module.ts
export function add(a: int, b: int): int {
  return a + b;
}
[23:44:28][/private/tmp/assembly-script-hello]$ cat foo.ts
import { add } from './module';

console.log('1+2=', add(1, 2));
[23:44:29][/private/tmp/assembly-script-hello]$ ./node_modules/.bin/ts-node foo.ts
1+2= 3
```

But when moved into node_modules:

```
[23:44:58][/private/tmp/assembly-script-hello]$ mv foo.ts node_modules/
[23:45:01][/private/tmp/assembly-script-hello]$ ./node_modules/.bin/ts-node node_modules/foo.ts
/private/tmp/assembly-script-hello/node_modules/foo.ts:1
(function (exports, require, module, __filename, __dirname) { import { add } from '../module';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/private/tmp/assembly-script-hello/node_modules/ts-node/src/index.ts:376:14)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (/private/tmp/assembly-script-hello/node_modules/ts-node/src/_bin.ts:177:12)
```

I can reproduce the issue by doing:

```sh
cd /tmp/
mkdir foobar
cd foobar
echo 'export function add(a: int, b: int): int { return a + b; }' > module.ts
echo '{"dependencies": {"assemblyscript": "https://github.com/dcodeIO/AssemblyScript.git"}}' > package.json
echo '{"extends": "./node_modules/assemblyscript/tsconfig.assembly.json"}' > tsconfig.json
npm install
./node_modules/.bin/asc module.ts -o module.wasm
```

**Comment by dcodeIO** [comment] 2017-06-20 14:00
Does this commit help?

**Comment by aiham** [comment] 2017-06-20 14:14
Unfortunately not.

```
[00:02:41][/private/tmp/assembly-script-hello]$ cat node_modules/.bin/asc
#!/usr/bin/env node
require("ts-node/register");
require("../cli/asc");
[00:02:44][/private/tmp/assembly-script-hello]$ yarn run build
yarn run v0.24.6
$ asc module.ts -o module.wasm
/private/tmp/assembly-script-hello/node_modules/assemblyscript/cli/asc/index.ts:3
import { Compiler } from "../../src/compiler";
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/private/tmp/assembly-script-hello/node_modules/ts-node/src/index.ts:376:14)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
error Command failed with exit code 1.
```

I've confirmed the repro steps listed above are valid by running them inside an isolated docker container.

**Comment by yahiko00** [comment] 2017-06-23 14:53
I also have troubles running the project example:

1. I've installed assemblyscript: `npm -g install assemblyscript`
2. I've cloned the repository locally.

My TypeScript version is:
tsc -v ==> 2.3.4
asc -v ==> 2.3.4

My package.json (unchanged) is:
```
{
  "name": "assemblyscript-examples-project",
  "description": "A pre-configured AssemblyScript project.",
  "dependencies": {
    "assemblyscript": "latest"
  },
  "scripts":{
    "build": "asc module.ts -o module.wasm"
  },
  "private": true
}
```

My tsconfig.json (unchanged) is:
```
{
  "extends": "./node_modules/assemblyscript/tsconfig.assembly.json"
}
```

When I'm trying to build: npm run build
A long error message occurs.

When I'm trying to run the command line manually: `asc module.ts -o module.wasm`
The following error message occurs: `error TS5023: Unknown compiler option '-o'`

When I tweak the package.json and the tsconfig.json to change the deprecated -o option to --outFile, the following error message occurs:
```
module.ts(3,24): error TS2304: Cannot find name 'int'.
module.ts(3,32): error TS2304: Cannot find name 'int'.
module.ts(3,38): error TS2304: Cannot find name 'int'.
```

**Comment by dcodeIO** [comment] 2017-06-23 17:10
It's not on npm, yet, so using the repo is the way to go currently.

**Comment by aiham** [comment] 2017-06-24 02:11
@dcodeIO It looks like `ts-node` cannot run a ts file that's inside `node_modules`. I'm not too familiar with TypeScript but I assume there's a setting which makes TypeScript ignore files within `node_modules`. I've reproduced this issue independent of AssemblyScript.

**Comment by aiham** [comment] 2017-06-24 02:13
Found it.

```
The "exclude" property defaults to excluding the node_modules, bower_components, jspm_packages and <outDir> directories when not specified.
```
http://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by dcodeIO** [comment] 2017-06-24 08:45
I see. Going to implement some checks there and if it's not a development install run the dist files instead.

**Comment by yahiko00** [comment] 2017-06-29 20:28
1. I've cloned the repo from the begining.
`$ git clone https://github.com/dcodeIO/AssemblyScript.git`

2. I've installed the asc compiler globally at the root of the project
`$ npm install -g`

3. I've built the example
```
cd examples/project/
npm run build
asc module.ts --text -o module.wat
```

... and it worked ;)

Thanks!

**Comment by dcodeIO** [comment] 2017-07-01 17:02
Closing this for now. In the near future, there'll of course be a pre-compiled npm package that takes away all the pain of setting up the package to use the compiler.

**Closed by dcodeIO** 2017-07-01 17:02 UTC
Labels: unsure
