### ISSUE TITLE
Compilation error in binaryen.ts

### ISSUE THREAD

**Issue by ir2331** [dcodeIO/AssemblyScript#55] opened 2017-06-20 16:01 UTC
I tried to compile the program and it gave me the following error message:
`c:\AssemblyScript\node_modules\binaryen\index.js:26
function(e){if(!(e instanceof ha))throw e;});a.inspect=function(){return"[Emscripten Module object]"}}else if(La)a.print||(a.print=print),"undefined"!=typeof printErr&&(a.printErr=printErr),a.read="undefined"!=typeof read?read:function(){throw"no read() available";},a.readBinary=function(e){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(e));e=read(e,"binary");v("object"===typeof e);return e},"undefined"!=typeof scriptArgs?a.arguments=scriptArgs:"undefined"!=typeof arguments&&(a.arguments=
                                  ^
`
`Error: unexpected type
    at Error (native)
    at Object.typeOf (c:\AssemblyScript\src\binaryen.ts:102:9)
    at Function.initialize (c:\AssemblyScript\src\reflection\function.ts:73:49)
    at Compiler.initializeFunction (c:\AssemblyScript\src\compiler.ts:429:18)
    at Class.initializeMethod (c:\AssemblyScript\src\reflection\class.ts:131:43)
    at Class.initialize (c:\AssemblyScript\src\reflection\class.ts:115:16)
    at Class.initialize (c:\AssemblyScript\src\reflection\class.ts:60:17)
    at Compiler.initializeClass (c:\AssemblyScript\src\compiler.ts:485:16)
    at Compiler.initialize (c:\AssemblyScript\src\compiler.ts:262:18)
    at Function.Compiler.compileProgram (c:\AssemblyScript\src\compiler.ts:129:14)
`

Therefore, I went to binaryen.ts and in both the functions typeOf and identifierOf added a default statement at the end of all the cases for the switch statement, commenting out the Throw Error line. 
The default statement in typeOf() returned i32 and the one in identifierOf returned "i". 

The value of type.kind was 6 when the program reached the default case for both typeOf and identifierOf.

This eliminates the error and compiles correctly to WASM. All this happened when the TypeScript test file was fib.ts.

**Comment by dcodeIO** [comment] 2017-06-20 19:57
I believe this is caused by a missing case for `sbyte` (that's kind 6). Should be fixed in master already.

**Closed** 2017-06-20 20:12 UTC
